name: Keep Render Alive

on:
  schedule:
    - cron: "2-59/5 * * * *"
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render
        run: |
          echo "----------->  Pinging Render"
          curl -fsS https://uypyog-migration-framework.onrender.com/actuator/health
          echo
          echo "<-----------  Render is alive"
